<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ggbootstrap"
 *
 * Auto generated by Extension Builder 2015-10-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ggbootstraptemplate',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Frederic Rouckhout, Chris Dorreman',
	'author_email' => 'frederic.rouckhout@goudengids.be, chris.dorreman@goudengids.be',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);